//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR.M.Antuh.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authorizations> Authorizations { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Contract> Contract { get; set; }
        public virtual DbSet<Export> Export { get; set; }
        public virtual DbSet<ExportMinerals> ExportMinerals { get; set; }
        public virtual DbSet<Minerals> Minerals { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Provider> Provider { get; set; }
        public virtual DbSet<PurschasedEquip> PurschasedEquip { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Reserve> Reserve { get; set; }
        public virtual DbSet<SocialProgram> SocialProgram { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypesOfContracts> TypesOfContracts { get; set; }
    }
}
