//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR.M.Antuh.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserve
    {
        public int ID_Reserve { get; set; }
        public int ID_Minerals { get; set; }
        public string Quantity { get; set; }
    
        public virtual Minerals Minerals { get; set; }
    }
}
