//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAuthorizations.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportMinerals
    {
        public string ID_ExportMinerals { get; set; }
        public int ID_Contracts { get; set; }
        public int ID_Minerals { get; set; }
        public string Quantity { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Minerals Minerals { get; set; }
    }
}
