//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAuthorizations.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurschasedEquip
    {
        public int ID_PurshasedEquip { get; set; }
        public int ID_Provider { get; set; }
        public string Name { get; set; }
        public decimal Cost { get; set; }
        public int ID_Staff { get; set; }
    
        public virtual Provider Provider { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
